import { answerRepository, ensureSecondRepository, readyRun, reveal, selectChoice, view } from './ui-helpers.mjs';
import { test, expect } from '@playwright/test';

test('registers a repository once with explicitly approved check commands', { tag: '@setup' }, async ({ page, request }) => {
  const state = await (await request.get('/api/state')).json();
  const path = state.projects[0].repositoryPath.replace(/repository$/, 'second');
  await page.goto('/');
  await page.getByLabel('Ticket or instructions').fill('Preserve this draft during setup');
  await page.goto('/admin/projects/new');
  await expect(page).toHaveURL(/\/admin\/projects\/new$/);
  await expect(page.locator('dialog')).toHaveCount(0);
  await page.getByLabel('Local repository path').fill(path); await page.getByRole('button', { name: 'Inspect', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('Second repository');
  await expect(page.getByRole('switch', { name: 'npm run test' })).toBeChecked(); await expect(page.getByRole('switch', { name: 'npm run dev' })).toHaveCount(0);
  await page.getByRole('switch', { name: 'npm run test' }).click(); await expect(page.getByRole('switch', { name: 'npm run test' })).not.toBeChecked();
  await page.getByRole('textbox', { name: 'Add a check command' }).fill('node -e process.exit(0)'); await page.getByRole('textbox', { name: 'Add a check command' }).press('Enter');
  await expect(page.getByRole('region', { name: 'Unsaved changes' })).toContainText('node -e process.exit(0)');
  await page.getByRole('tab', { name: /^Shortcuts/ }).click(); await page.getByRole('button', { name: 'Edit shortcut *.md', exact: true }).click();
  await expect(page.getByLabel('If only these files change')).toHaveValue('*.md\ndocs/**');
  await page.getByRole('button', { name: 'node', exact: true }).click(); await expect(page.getByRole('button', { name: 'node', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Save repository', exact: true }).click();
  await expect(page.getByLabel('Ticket or instructions')).toHaveValue('Preserve this draft during setup');
  await expect(page.getByLabel('Repository question')).toContainText('Second repository');
  await page.reload(); await expect(page.getByLabel('Ticket or instructions')).toHaveValue('Preserve this draft during setup');
  const saved = (await (await request.get('/api/projects')).json()).find(project => project.name === 'Second repository');
  expect(saved.validation.map(step => step.id)).toEqual(['node']); expect(saved.validation[0].args).toEqual(['-e', 'process.exit(0)']); expect(saved.checkScopes).toEqual([{ id: 'text-only', paths: ['*.md', 'docs/**'], checks: ['node'] }]);
});

test('admin shows accurate token totals and history without changing user view', { tag: '@setup' }, async ({ page, request }) => {
  await readyRun(request, 'Report usage for this run');
  await page.goto('/'); await expect(page.getByRole('link', { name: 'Usage', exact: true })).toBeHidden();
  await page.getByRole('link', { name: 'Settings', exact: true }).click(); await page.getByRole('link', { name: 'Usage', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Usage', exact: true })).toBeVisible();
  await expect(page.locator('#admin-metrics')).toContainText('Reported tokens');
  await page.getByRole('tab', { name: /^History/ }).click(); await expect(page.locator('#admin-history')).toContainText('150');
  await page.getByRole('link', { name: 'All work', exact: true }).click(); await expect(page.getByLabel('Ticket or instructions')).toBeVisible();
});

test('selects repositories from local folders, typed paths and instructions without starting a run', { tag: '@setup' }, async ({ page, request }) => {
  await ensureSecondRepository(request);
  const state = await (await request.get('/api/state')).json(), project = state.projects[0];
  await page.goto('/');
  await page.getByLabel('Ticket or instructions').fill(`Update ${project.repositoryPath}`);
  await expect(page.getByLabel('Repository', { exact: true })).toHaveAttribute('data-value', project.id);
  await page.goto('/admin/projects/new');
  await expect(page).toHaveURL(/\/admin\/projects\/new$/);
  await page.getByRole('button', { name: 'Browse folders', exact: true }).click();
  await page.getByLabel('Folder location').fill(project.repositoryPath);
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  await expect(page.getByLabel('Local folders')).toContainText(project.repositoryPath);
  await page.getByRole('button', { name: 'Choose this folder' }).click();
  await expect(page.getByLabel('Local folders')).toHaveCount(0);
  await expect(page.getByLabel('Local repository path')).toHaveValue(project.repositoryPath);
  await page.getByLabel('Local repository path').fill('/definitely-missing-dispatch-folder');
  await page.getByRole('button', { name: 'Inspect', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('does not exist');
  await page.goto('/');
  await expect(page.getByLabel('Ticket or instructions')).toHaveValue(`Update ${project.repositoryPath}`);
  await page.getByLabel('Ticket or instructions').fill('Update Browser test repository and Second repository');
  await expect(page.getByRole('button', { name: 'dispatch', exact: true })).toBeDisabled();
  await answerRepository(page, project.name);
  await expect(page.getByRole('button', { name: 'dispatch', exact: true })).toBeEnabled();
  expect((await (await request.get('/api/state')).json()).runs.length).toBe(state.runs.length);
});

test('repository settings save optional review and show revision-bound verdicts', { tag: '@setup' }, async ({ page, request }) => {
  const project = await ensureSecondRepository(request);
  await page.goto(`/admin/projects/${project.id}`);
  await page.getByRole('tab', { name: /^Extras/ }).click();
  await expect(page.getByRole('switch', { name: 'Use Example Tracker' })).not.toBeChecked();
  await page.getByRole('switch', { name: 'Second opinion' }).click();
  await expect(page.getByRole('region', { name: 'Unsaved changes' })).toContainText('Unsaved changes');
  await page.getByRole('button', { name: 'Save repository', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Unsaved changes' })).toHaveCount(0);
  await expect(page.getByRole('switch', { name: 'Second opinion' })).toBeChecked();
  await page.goto('/');
  await page.getByLabel('Ticket or instructions').fill('Review the local result');
  await answerRepository(page, 'Second repository');
  await page.getByRole('button', { name: 'dispatch', exact: true }).click();
  await expect(page.locator('.run-state')).toContainText('Ready for review');
  await view(page, 'Checks');
  await expect(page.getByRole('heading', { name: 'Independent review', exact: true })).toHaveCount(1);
  await expect(page.locator('.checks-tile')).toContainText('Attempt 1 · passed');
  await view(page, 'Result');
  await expect(page.locator('.run-metrics')).toContainText('175');
});

test('setup discovers models and the composer keeps an explicit model choice with accessible custom controls', { tag: '@setup' }, async ({ page, request }, testInfo) => {
  const before = await (await request.get('/api/state')).json();
  await page.goto('/setup#providers'); await expect(page.getByRole('heading', { name: 'Integrations', exact: true })).toBeVisible();
  await expect(page.getByText('Off', { exact: true })).toHaveCount(4);
  await expect(page.getByText('Connected', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Check connections' }).click();
  await expect(page.getByText('Connected', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Models', exact: true }).click();
  await reveal(page, page.getByRole('button', { name: 'Refresh models' })); await page.getByRole('button', { name: 'Refresh models' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Test model catalog' })).toBeVisible();
  expect((await (await request.get('/api/state')).json()).runs.length).toBe(before.runs.length);
  await page.reload(); await expect(page.getByRole('status').filter({ hasText: 'Test model catalog' })).toBeVisible();
  await reveal(page, page.getByRole('button', { name: 'Refresh models' })); await page.getByRole('button', { name: 'Refresh models' }).hover();
  await expect(page.getByRole('tooltip')).toContainText('Refresh models');
  await expect(page.getByRole('link', { name: 'Settings', exact: true })).toHaveAttribute('aria-current', 'page');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: testInfo.outputPath('dispatch-setup-mobile.png'), fullPage: true });
  await page.goto('/'); await expect(page.getByLabel('Model', { exact: true })).toHaveAttribute('data-value', '');
  await selectChoice(page, 'Model', 'codex:test-luna');
  await page.getByLabel('Ticket or instructions').fill('Fix a README typo');
  await answerRepository(page, 'Browser test repository');
  const [response] = await Promise.all([page.waitForResponse(response => response.url().endsWith('/api/runs') && response.status() === 201), page.getByRole('button', { name: 'dispatch', exact: true }).click()]);
  const run = await response.json(); expect(run.execution.model).toBe('test-luna'); expect(run.execution.effort).toBe('low');
  await expect(page.locator('.run-state')).toContainText('Ready for review');
  await page.goto('/');
  await selectChoice(page, 'Model', 'codex:test-sol');
  const effort = page.getByRole('slider', { name: 'Model reasoning' });
  await expect(effort).toHaveAttribute('aria-valuetext', 'high');
  await effort.focus(); await page.keyboard.press('Home'); await expect(effort).toHaveAttribute('aria-valuetext', 'low');
  await page.reload(); await expect(page.getByLabel('Model', { exact: true })).toHaveAttribute('data-value', 'codex:test-sol');
  await expect(page.getByRole('slider', { name: 'Model reasoning' })).toHaveAttribute('data-value', 'low');
});

test('the composer asks which repository to use and the answer applies to that ticket only', { tag: '@setup' }, async ({ page, request }) => {
  await ensureSecondRepository(request);
  const before = await (await request.get('/api/state')).json();
  await page.goto('/');
  await page.getByLabel('Ticket or instructions').fill('Fix an unspecified screen');
  await expect(page.getByLabel('Repository question')).toContainText('Which repository');
  await expect(page.getByRole('button', { name: 'dispatch', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Second repository', exact: true }).click();
  await expect(page.getByLabel('Repository question')).toHaveCount(0);
  await expect(page.getByLabel('Repository', { exact: true })).toContainText('Second repository');
  await expect(page.getByRole('button', { name: 'dispatch', exact: true })).toBeEnabled();
  await page.getByLabel('Ticket or instructions').pressSequentially(' quickly');
  await expect(page.getByLabel('Repository question')).toHaveCount(0);
  await expect(page.getByLabel('Repository', { exact: true })).toContainText('Second repository');
  await page.getByLabel('Ticket or instructions').fill('');
  await page.getByLabel('Ticket or instructions').fill('Fix another unspecified screen');
  await expect(page.getByLabel('Repository question')).toContainText('Which repository');
  await page.reload(); await expect(page.getByLabel('Repository question')).toContainText('Which repository');
  expect((await (await request.get('/api/state')).json()).runs.length).toBe(before.runs.length);
});

test('turning on another provider checks it, lists its models and routes a dispatch to it', { tag: '@setup' }, async ({ page, request }) => {
  await page.goto('/setup#providers');
  const card = page.locator('.connection-row').filter({ has: page.getByRole('switch', { name: 'Claude Code', exact: true }) });
  await expect(card.getByText('Off', { exact: true })).toBeVisible();
  await card.getByRole('switch', { name: 'Claude Code', exact: true }).click();
  await expect(card.getByRole('switch', { name: 'Claude Code', exact: true })).toBeChecked();
  await expect(card.getByText('Connected', { exact: true })).toBeVisible();
  await page.goto('/');
  await selectChoice(page, 'Model', 'claude:opus');
  await expect(page.getByLabel('Model', { exact: true })).toContainText('Claude Code · Opus');
  await page.getByLabel('Ticket or instructions').fill('Route this to Claude');
  await answerRepository(page, 'Browser test repository');
  const [response] = await Promise.all([page.waitForResponse(response => response.url().endsWith('/api/runs') && response.status() === 201), page.getByRole('button', { name: 'dispatch', exact: true }).click()]);
  const run = await response.json(); expect(run.provider).toBe('claude'); expect(run.execution).toMatchObject({ provider: 'claude', model: 'opus', effort: null });
  await expect(page.locator('.run-state')).toContainText('Ready for review');
  await expect(page.getByLabel('Conversation history')).toContainText('Claude Code');
  await request.post('/api/providers', { data: { id: 'claude', enabled: false } });
  await page.goto('/'); await expect(page.getByLabel('Model', { exact: true })).not.toContainText('Claude Code');
});

test('turning on local models reveals endpoint settings that save and validate', { tag: '@setup' }, async ({ page, request }) => {
  await page.goto('/setup#providers');
  await expect(page.getByRole('switch', { name: 'Use local models' })).toHaveCount(0);
  await page.goto('/setup#local-models');
  const card = page.locator('.connection-row').filter({ has: page.getByRole('switch', { name: 'Use local models' }) });
  await expect(page.getByLabel('Agent', { exact: true })).toHaveCount(0);
  await card.getByRole('switch', { name: 'Use local models' }).click();
  await expect(card.getByText('Connected', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Ollama URL')).toHaveValue(/^http:\/\/127\.0\.0\.1:\d+$/);
  await expect(page.locator('.local-agent')).toContainText('only writes text');
  await selectChoice(page, 'Agent', 'pi');
  await expect(page.locator('.local-agent')).toContainText('only with Full access');
  expect((await (await request.get('/api/workspace')).json()).localAgent).toBe('pi');
  await expect(page.locator('.endpoint-row').first()).toContainText('Connected · 1 model');
  await expect(page.getByRole('button', { name: 'Save and connect' })).toBeDisabled();
  await page.getByRole('button', { name: 'Add endpoint' }).click();
  await expect(page.locator('.endpoint-row').nth(1)).toContainText('Not saved');
  await page.getByLabel('Endpoint 2 name').fill('GPU box');
  await page.getByLabel('GPU box URL').fill('http://user:secret@10.0.0.5:11434');
  await page.getByRole('button', { name: 'Save and connect' }).click();
  await expect(page.getByRole('alert')).toContainText('without credentials');
  await page.getByLabel('GPU box URL').fill('http://10.0.0.5:11434/');
  await page.getByRole('button', { name: 'Save and connect' }).click();
  await expect(page.getByRole('button', { name: 'Save and connect' })).toBeDisabled();
  expect((await (await request.get('/api/workspace')).json()).localEndpoints.map(endpoint => [endpoint.id, endpoint.url])).toContainEqual(['gpu-box', 'http://10.0.0.5:11434']);
  await page.goto('/');
  await selectChoice(page, 'Model', 'local-models:ollama/qwen3.6:latest');
  await expect(page.getByLabel('Model', { exact: true })).toContainText('qwen3.6:latest');
  await request.post('/api/local-endpoints', { data: { endpoints: [] } });
  await request.post('/api/local-agent', { data: { agent: 'claude' } });
  await request.post('/api/providers', { data: { id: 'local-models', enabled: false } });
});

test('settings switch agent access and the usage page shows plan limits and tokens per provider', { tag: '@setup' }, async ({ page, request }) => {
  await page.goto('/setup#access');
  const access = page.getByRole('group', { name: 'Agent access' });
  await expect(access.getByRole('button', { name: 'Home folder' })).toHaveAttribute('aria-pressed', 'true');
  await access.getByRole('button', { name: 'Full access' }).click();
  await expect(access.getByRole('button', { name: 'Full access' })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByText(/No sandbox/)).toBeVisible();
  expect((await (await request.get('/api/state')).json()).accessMode).toBe('full');
  await access.getByRole('button', { name: 'Home folder' }).click();
  await expect(access.getByRole('button', { name: 'Home folder' })).toHaveAttribute('aria-pressed', 'true');
  await page.goto('/admin');
  const codex = page.getByRole('article', { name: 'Codex usage' });
  await expect(codex.getByRole('meter', { name: 'Weekly limit used' })).toHaveAttribute('aria-valuenow', '42');
  await expect(codex).toContainText('test-plan'); await expect(codex).toContainText(/Output tokens|No runs yet/);
});

test('standing rules, protected paths and remote tracking are saved from repository settings', { tag: '@setup' }, async ({ page, request }) => {
  const project = (await (await request.get('/api/projects')).json()).find(item => item.name === 'Browser test repository');
  await page.goto(`/admin/projects/${project.id}`);
  await page.getByRole('tab', { name: /^Agent rules/ }).click();
  const rule = page.getByRole('textbox', { name: 'Add a rule' });
  await rule.fill('Prefer staging.'); await rule.press('Enter'); await rule.fill('Never use Prisma.'); await rule.press('Enter');
  await page.getByRole('textbox', { name: 'Add a protected path' }).fill('src/legacy/**'); await page.getByRole('button', { name: 'Add a protected path', exact: true }).click();
  await page.getByRole('tab', { name: /^Extras/ }).click(); await page.getByRole('switch', { name: /^Start from origin/ }).click();
  await page.getByRole('button', { name: 'Save repository', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Unsaved changes' })).toHaveCount(0);
  const saved = (await (await request.get('/api/projects')).json()).find(item => item.id === project.id);
  expect(saved.instructions).toEqual(['Prefer staging.', 'Never use Prisma.']); expect(saved.protectedPaths).toEqual(['src/legacy/**']); expect(saved.trackRemote).toBe(false);
  await request.post(`/api/projects/${project.id}`, { data: { ...saved, confirmed: true, instructions: [], protectedPaths: [], trackRemote: true } });
});

test('the Brain lists remembered rules, toggles them, forgets them from the composer and lives in settings', { tag: '@setup' }, async ({ page, request }) => {
  const state = await (await request.get('/api/state')).json();
  const project = state.projects.find(project => project.name === 'Browser test repository');
  await request.post(`/api/projects/${project.id}/instructions`, { data: { text: 'Never use Prisma in the brain test' } });
  await page.goto('/'); await expect(page.getByRole('navigation', { name: 'Workspace' }).getByRole('link', { name: 'Brain', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'Settings', exact: true }).click(); await page.getByRole('navigation', { name: 'Settings' }).getByRole('link', { name: 'Brain', exact: true }).click();
  await expect(page).toHaveURL(/\/brain$/); await expect(page.getByRole('heading', { name: 'Brain', exact: true })).toBeVisible();
  await expect(page.getByRole('img', { name: /^Memory graph/ })).toBeVisible();
  await page.getByLabel('Filter').fill('Prisma in the brain');
  await page.getByRole('navigation', { name: 'Matches' }).getByRole('button', { name: 'Never use Prisma in the brain test' }).click();
  const entry = page.getByRole('complementary', { name: 'Selected memory' }).locator('.brain-entry').filter({ hasText: 'Never use Prisma in the brain test' });
  await expect(entry).toBeVisible(); await expect(entry.getByText('You')).toBeVisible();
  await entry.getByLabel('Enabled').uncheck();
  await expect.poll(async () => (await (await request.get('/api/projects')).json()).find(item => item.id === project.id).instructions).not.toContain('Never use Prisma in the brain test');
  await page.getByLabel('Filter').fill('nothing matches this');
  await expect(page.getByText('Nothing matches the filter.')).toBeVisible();
  await page.goto('/');
  await page.getByLabel('Ticket or instructions').fill('/forget prisma brain test');
  await page.getByRole('button', { name: 'Forget', exact: true }).click();
  const card = page.getByLabel('Forget memory');
  await expect(card).toContainText('Never use Prisma in the brain test');
  const match = card.getByRole('listitem').filter({ hasText: 'Never use Prisma in the brain test' });
  await match.getByRole('button', { name: 'Forget', exact: true }).click(); await expect(match).toHaveCount(0);
  if (await card.count()) await card.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(card).toBeHidden(); await expect(page.getByLabel('Ticket or instructions')).toHaveValue('');
  const brain = await (await request.get(`/api/brain?projectId=${project.id}&kind=rule`)).json();
  expect(brain.entries.map(item => item.text)).not.toContain('Never use Prisma in the brain test');
});
